export const Figures = [
    {
        id: "1",
        title: "Doki Doki Literature Club Yuri Nendroid Figure",
        category: "PRE-ORDER",
        company: "Good Smile",
        image: require("./assets/figures/yuriddlc/yurifigure.jpg"),
        bottomimage: require("./assets/figures/yuriddlc/yurifigurebottom.jpg"),
        slider: [require("./assets/figures/yuriddlc/yurifiguressliderOne.jpeg"), require("./assets/figures/yuriddlc/yurifiguressliderTwo.jpeg"), require("./assets/figures/yuriddlc/yurifiguressliderThree.jpeg"), require("./assets/figures/yuriddlc/yurifiguressliderFour.jpeg")],
        price: "42.99",
        release: "2024/05",
        size: "100mm",
        material: "PVC, ABS"
    },
    {
        id: "2",
        title: "Sylphina Special Ver. illustration by oekakizuki 1/6",
        category: "PRE-ORDER",
        company: "PinkMango",
        image: require("./assets/figures/sylphina/sylphinafigure.jpg"),
        bottomimage: require("./assets/figures/sylphina/sylphinafigurebottom.jpg"),
        slider: [require("./assets/figures/sylphina/sylphinafigureslideOne.jpg"), require("./assets/figures/sylphina/sylphinafigureslideTwo.jpg"), require("./assets/figures/sylphina/sylphinafigureslideThree.jpg"), require("./assets/figures/sylphina/sylphinafigureslideFour.jpg"), require("./assets/figures/sylphina/sylphinafigureslideFive.jpg")],
        price: "169.30",
        release: "2024/11",
        size: "1/6",
        material: "PVC, ABS"
    },
    {
        id: "3",
        title: "Milk Time - Yuu 1/7 Complete Figure",
        category: "PRE-ORDER",
        company: "PLUM",
        image: require("./assets/figures/yuu/yuufigure.jpg"),
        bottomimage: require("./assets/figures/yuu/yuufigurebottom.jpg"),
        slider: [require("./assets/figures/yuu/yuufigureslideOne.jpg"), require("./assets/figures/yuu/yuufigureslideTwo.jpg"), require("./assets/figures/yuu/yuufigureslideThree.jpg"), require("./assets/figures/yuu/yuufigureslideFour.jpg"), require("./assets/figures/yuu/yuufigureslideFive.jpg")],
        price: "134.75",
        release: "2024/08",
        size: "1/7",
        material: "PVC, ABS"
    },
    {
        id: "4",
        title: "HaneAme SINFUL NUN 72 Sigils of Solomon Angel Crocell Complete Figure",
        category: "PRE-ORDER",
        company: "Good Smile",
        image: require("./assets/figures/hane/hanefigure.jpg"),
        bottomimage: require("./assets/figures/hane/hanefigurebottom.jpg"),
        slider: [require("./assets/figures/hane/hanefigureslideOne.jpg"), require("./assets/figures/hane/hanefigureslideTwo.jpg"), require("./assets/figures/hane/hanefigureslideThree.jpg"), require("./assets/figures/hane/hanefigureslideFour.jpg")],
        price: "167.87",
        release: "2025/02",
        size: "1/6",
        material: "Plastic"
    },
    {
        id: "5",
        title: "Date A Live Natsumi 1/7 Complete Figure",
        category: "PRE-ORDER",
        company: "Bellfine",
        image: require("./assets/figures/natsumi/natsumifigure.jpg"),
        bottomimage: require("./assets/figures/natsumi/natsumifigurebottom.jpg"),
        slider: [require("./assets/figures/natsumi/natsumifigureslideOne.jpg"), require("./assets/figures/natsumi/natsumifigureslideTwo.jpg"), require("./assets/figures/natsumi/natsumifigureslideThree.jpg"), require("./assets/figures/natsumi/natsumifigureslideFour.jpg"), require("./assets/figures/natsumi/natsumifigureslideFive.jpg")],
        price: "126.00",
        release: "2024/10",
        size: "1/7",
        material: "PVC, ABS"
    },
    {
        id: "6",
        title: "[Bonus] Bunnystein Fantasy Sumire Bunny Ver. 1/4 Complete Figure",
        category: "PRE-ORDER",
        company: "BINDing",
        image: require("./assets/figures/sumire/sumirefigure.jpg"),
        bottomimage: require("./assets/figures/sumire/sumirefigurebottom.jpg"),
        slider: [require("./assets/figures/sumire/sumirefigureslideOne.jpg"), require("./assets/figures/sumire/sumirefigureslideTwo.jpg"), require("./assets/figures/sumire/sumirefigureslideThree.jpg"), require("./assets/figures/sumire/sumirefigureslideFour.jpg"), require("./assets/figures/sumire/sumirefigureslideFive.jpg")],
        price: "256.67",
        release: "2024/12",
        size: "1/4",
        material: "PVC, ABS, Polyester"
    },
    {
        id: "7",
        title: "Fumi Fumi Chloe 1/6 Complete Figure(Pre-order)",
        category: "PRE-ORDER",
        company: "Charm",
        image: require("./assets/figures/chloe/chloefigure.jpg"),
        bottomimage: require("./assets/figures/chloe/chloefigurebottom.jpg"),
        slider: [require("./assets/figures/chloe/chloefigureslideOne.jpg"), require("./assets/figures/chloe/chloefigureslideTwo.jpg"), require("./assets/figures/chloe/chloefigureslideThree.jpg"), require("./assets/figures/chloe/chloefigureslideFour.jpg"), require("./assets/figures/chloe/chloefigureslideFive.jpg")],
        price: "187.77",
        release: "2024/10",
        size: "1/6",
        material: "PVC, ABS"
    },
    {
        id: "8",
        title: "Azur Lane Taiho -Still Illustration ver.- 1/4 Complete Figure(Pre-order)",
        category: "PRE-ORDER",
        company: "Alphamax",
        image: require("./assets/figures/taiho/taihofigure.jpg"),
        bottomimage: require("./assets/figures/taiho/taihofigurebottom.jpg"),
        slider: [require("./assets/figures/taiho/taihofigureslideOne.jpg"), require("./assets/figures/taiho/taihofigureslideTwo.jpg"), require("./assets/figures/taiho/taihofigureslideThree.jpg"), require("./assets/figures/taiho/taihofigureslideFour.jpg")],
        price: "240.66",
        release: "2025/01",
        size: "1/4",
        material: "PVC"
    },
    {
        id: "9",
        title: "Honkai: Star Rail Tingyun 1/10 Complete Figure(Pre-order)",
        category: "PRE-ORDER",
        company: "Myethos",
        image: require("./assets/figures/tinguyn/tingyunfigure.jpg"),
        bottomimage: require("./assets/figures/tinguyn/tingyunfigurebottom.jpg"),
        slider: [require("./assets/figures/tinguyn/tinguynfigureslideOne.jpg"), require("./assets/figures/tinguyn/tinguynfigureslideTwo.jpg"), require("./assets/figures/tinguyn/tinguynfigureslideThree.jpg"), require("./assets/figures/tinguyn/tinguynfigureslideFour.jpg")],
        price: "33.51",
        release: "2024/10",
        size: "1/10",
        material: "PVC, ABC, Metal"
    },
    {
        id: "10",
        title: "Evangelion Rei Ayanami Whisper of Flower Ver. 1/7 Complete Figure(Released)",
        category: "RELEASED",
        company: "Myethose",
        image: require("./assets/figures/ayanami/ayanamifigure.jpg"),
        bottomimage: require("./assets/figures/ayanami/ayanamifigurebottom.jpg"),
        slider: [require("./assets/figures/ayanami/ayanamifigureslideOne.jpg"), require("./assets/figures/ayanami/ayanamifigureslideTwo.jpg"), require("./assets/figures/ayanami/ayanamifigureslideThree.jpg"), require("./assets/figures/ayanami/ayanamifigureslideFour.jpg"), require("./assets/figures/ayanami/ayanamifigureslideFive.jpg")],
        price: "139.74",
        size: "1/7",
        material: "PVC, ABC, Metal"
    },
    {
        id: "11",
        title: "Nendoroid The Witcher 3 Wild Hunt Yennefer(Released)",
        category: "ORDER-CLOSED",
        company: "Good Smile",
        image: require("./assets/figures/yennifer/yenniferfigure.jpg"),
        bottomimage: require("./assets/figures/yennifer/yenniferfigurebottom.jpg"),
        slider: [require("./assets/figures/yennifer/yenniferfigureslideOne.jpg"), require("./assets/figures/yennifer/yenniferfigureslideTwo.jpg"), require("./assets/figures/yennifer/yenniferfigureslideThree.jpg")],
        price: "28.26",
        size: "100mm",
        material: "PVC, ABC"
    },
    {   
        id: "12",
        title: "Attack on Titan Levi Renewal Package ver. 1/8 Complete Figure(Released)",
        category: "RELEASED",
        company: "Kotobukiya",
        image: require("./assets/figures/levi/levifigure.jpg"),
        bottomimage: require("./assets/figures/levi/levifigurebottom.jpg"),
        slider: [require("./assets/figures/levi/levifigureslideOne.jpg"), require("./assets/figures/levi/levifigureslideTwo.jpg"), require("./assets/figures/levi/levifigureslideThree.jpg"), require("./assets/figures/levi/levifigureslideFour.jpg"), require("./assets/figures/levi/levifigureslideFive.jpg")],
        price: "90.61",
        size: "1/8",
        material: "PVC"
    },
    {
        id: "13",
        title: "Shinobi Master Senran Kagura: New Link Fubuki Bunny Ver. 1/4 Complete Figure(Pre-order)",
        category: "PRE-ORDER",
        company: "FREEing",
        image: require("./assets/figures/fubuki/fubukifigure.jpg"),
        bottomimage: require("./assets/figures/fubuki/fubukifigurebottom.jpg"),
        slider: [require("./assets/figures/fubuki/fubukifigureslideOne.jpg"), require("./assets/figures/fubuki/fubukifigureslideTwo.jpg"), require("./assets/figures/fubuki/fubukifigureslideThree.jpg"), require("./assets/figures/fubuki/fubukifigureslideFour.jpg"), require("./assets/figures/fubuki/fubukifigureslideFive.jpg")],
        price: "256.67",
        release: "2024/12",
        size: "1/4",
        material: "Plastic"
    },
    {
        id: "14",
        title: "Azur Lane Hammann Kai 1/7 Complete Figure(Pre-order)",
        category: "PRE-ORDER",
        company: "Plum",
        image: require("./assets/figures/hammann/hammannfigure.jpg"),
        bottomimage: require("./assets/figures/hammann/hammannfigurebottom.jpg"),
        slider: [require("./assets/figures/hammann/hammannfigureslideOne.jpg"), require("./assets/figures/hammann/hammannfigureslideTwo.jpg"), require("./assets/figures/hammann/hammannfigureslideThree.jpg"), require("./assets/figures/hammann/hammannfigureslideFour.jpg"), require("./assets/figures/hammann/hammannfigureslideFive.jpg")],
        price: "112.07",
        release: "2024/07",
        size: "1/7",
        material: "PVC"
    },

    {
        id: "15",
        title: "Arknights Amiya: Newsgirl VER. 1/7 Complete Figure(Pre-order).",
        category: "PRE-ORDER",
        company: "Good Smile",
        image: require("./assets/figures/newsgirl/newsgirlfigure.jpg"),
        bottomimage: require("./assets/figures/newsgirl/newsgirlfigurebottom.jpg"),
        slider: [require("./assets/figures/newsgirl/newsgirlfigureslideOne.jpg"), require("./assets/figures/newsgirl/newsgirlfigureslideTwo.jpg"), require("./assets/figures/newsgirl/newsgirlfigureslideThree.jpg"), require("./assets/figures/newsgirl/newsgirlfigureslideFour.jpg"), require("./assets/figures/newsgirl/newsgirlfigureslideFive.jpg")],
        price: "125.09",
        release: "2024/10",
        size: "1/7",
        material: "Plastic"
    },
    {
        id: "16",
        title: "Attack on Titan Mikasa Ackerman 1/8 Complete Figure(Pre-order)",
        category: "PRE-ORDER",
        company: "Good Smile",
        image: require("./assets/figures/mikasa/mikasafigure.jpg"),
        bottomimage: require("./assets/figures/mikasa/mikasafigurebottom.jpg"),
        slider: [require("./assets/figures/mikasa/mikasafigureslideOne.jpg"), require("./assets/figures/mikasa/mikasafigureslideTwo.jpg"), require("./assets/figures/mikasa/mikasafigureslideThree.jpg")],
        price: "118.35",
        release: "2024/12",
        size: "1/8",
        material: "Plastic"
    },

]